image: localhost:5000/qt-runner:v1

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - gcc --version
    - cmake --version
    - mkdir build && cd build
    - cmake ..
    - make
    - cd tests
    - ctest
    - cd ..
    - echo 'cmake --install' does not exists until v3.15
    - sudo env PATH=$PATH cmake --build . --target install
    - cd ..
    - dex --version
