
language: cpp

before_install:
  - sudo apt-get update
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  - travis_retry wget --no-check-certificate https://cmake.org/files/v3.17/cmake-3.17.0-Linux-x86_64.tar.gz
  - tar -xvf cmake-3.17.0-Linux-x86_64.tar.gz > /dev/null
  - mv cmake-3.17.0-Linux-x86_64 cmake-install
  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  - cd ${TRAVIS_BUILD_DIR}
  - sudo apt-get -y install clang-8 libc++-8-dev libc++abi-8-dev 

before_script:
  - cmake --version
  - mkdir build
  - cd build
  - set -e

matrix:
  include:
  - os: linux
    dist: focal
    name: Clang 8.0
    compiler: clang
    env:
      - CC=clang-8
      - CXX=clang++-8
    script:
      - cmake ..
      - make
      - cd tests
      - ctest
      - cd ..
      - echo 'cmake --install' does not exists until v3.15
      - sudo env PATH=$PATH cmake --build . --target install
      - cd ..
      - dex --version
  - os: linux
    dist: focal
    name: Clang 9.0
    compiler: clang
    env:
      - CC=clang-9
      - CXX=clang++-9
    script:
      - sudo apt-get -y install clang-9 libc++-9-dev libc++abi-9-dev 
      - cmake ..
      - make
      - cd tests
      - ctest
      - cd ..
      - echo 'cmake --install' does not exists until v3.15
      - sudo env PATH=$PATH cmake --build . --target install
      - cd ..
      - dex --version
  - os: linux
    dist: bionic
    name: GCC 8 (coverage)
    env:
      - CC=gcc-8
      - CXX=g++-8
    compiler: gcc-8
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-8
          - g++-8
    script:
      - cmake -DENABLE_COVERAGE=ON ..
      - make
      - cd tests
      - ctest
      - cd ..
      - cd ..
      - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-8 10
      - gcov --version
      - bash <(curl -s https://codecov.io/bash)
