
image: Visual Studio 2019

clone_depth: 3

platform:
  - x64

configuration:
  - Release
  
matrix:
  fast_finish: false

init:
  - cmd: cmake --version

install:
  - git submodule update --init --recursive

before_build:
  - mkdir build
  - cd build
  - cmake ..

build_script:
  - cmake --build . --config Release -- %MSBUILD_ARGS%

artifacts:
  - path: release\dex-setup.exe
    name: dex-setup.exe

after_build:
  - make-release.bat
  - cd ..\release
  - dex --version
  - cd ..
  - set "PATH=C:\Program Files (x86)\NSIS;%PATH%"
  - create-installer.bat
  - cd build

test_script:
  - cd tests
  - ctest . -C Release
